### ISSUE TITLE
object 'min_gDNA_count' not found

### ISSUE THREAD

**Issue by manueltar** [Jeremy37/rgenie#2]
Dear Jeremy,

Thank for the tool support. I am getting an error message in the alignment_analysis and I cannot understand it.

I run the grep analysis on all my samples and it goes well. Then I run the alignment analysis and some of my variants crash the analysis. The message I get is:

Error in get_uns_data(replicate.udp.df, replicates.df = replicates, region_name = region$name) :
  object 'min_gDNA_count' not found

It only happens after it finishes reading the gDNA samples. I have tried removing the specific sample in which the error is reported but it is then reported in the previous one. I am happy to provide the files. Best regards,

**Comment by Jeremy37** [comment]
Thanks for the note – I’ve just had a look, and it seems this is a bug. I think I’ve fixed it now, and I’ve checked the change in to github.
Could you reinstall using devtools as described on the github page, and see if it’s working for you now?
